fix(ui): animation updates [wip]
tari-project/universe pull request #1229
Opened 2024-12-11 09:59 UTC by shanimal08

Description
---

Motivation and Context
---

How Has This Been Tested?
---

What process can a PR reviewer use to test or verify this change?
---

Breaking Changes
---

- [x] None
- [ ] Requires data directory on base node to be deleted
- [ ] Requires hard fork
- [ ] Other - Please specify

2025-01-09 10:45 UTC, Misieq01 commented on src/App/AppWrapper.tsx
>      }, []);
We won't be bringing it back ?

2025-01-09 10:48 UTC, shanimal08 commented on src/App/AppWrapper.tsx
>      }, []);
yea but it always exists in github :D just a pet peeve of mine to leave in big chunks of commented code, but i don't mind adding it back if you want? :D

2025-01-09 10:49 UTC, Misieq01 commented on src/containers/floating/StagedSecurity/sections/SeedPhrase/SeedPhrase.tsx
> +    useEffect(() => {
I don't think we need useEffect and useState here as words come with props so it will be rerendered either way

2025-01-09 10:51 UTC, shanimal08 commented on src/containers/floating/StagedSecurity/sections/SeedPhrase/SeedPhrase.tsx
> +    useEffect(() => {
oh i updated `eslint-plugin-react-hooks` and it threw an error because of that loop out in the open ☹️ 

i can revert and revert the update?

2025-01-09 10:51 UTC, MCozhusheck requested changes

2025-01-09 10:51 UTC, MCozhusheck commented on src/containers/floating/StagedSecurity/sections/SeedPhrase/SeedPhrase.tsx
> +    }, [words]);
is this useEffect necessary ? `words` comes from props so changes in `words` will change wordGroups anyway

2025-01-09 10:51 UTC, MCozhusheck commented on src/containers/phase/Setup/components/AppVersion.tsx
> +        let fetched = false;
is this variable necessary ? It's local variable if we want to verify we fetch only once we should use `useState` or `useRef` variable.

2025-01-09 10:51 UTC, Misieq01 commented on src/App/AppWrapper.tsx
>      }, []);
I think its easier to uncomment code then look back through commit history but won't fight on it haha :D

2025-01-09 10:55 UTC, shanimal08 commented on src/containers/floating/StagedSecurity/sections/SeedPhrase/SeedPhrase.tsx
> +    }, [words]);
only changed it after the package bump https://github.com/tari-project/universe/pull/1229#discussion_r1908542970

 but yeah i wouldn't do that normally 😬 lmk if i should revert the update and these changes or just leave as is?

2025-01-09 10:59 UTC, Misieq01 commented on src/containers/phase/Setup/components/AppVersion.tsx
>      useEffect(() => {
I don't think `let fetched` make a difference here its defined in scope of useEffect so it won't be preserved between executions of this useEffect

2025-01-09 11:00 UTC, shanimal08 commented on src-tauri/src/main.rs
> +
neat, thanks! should i do the same for the `miner_metrics` emit loop just above?:D

2025-01-09 11:03 UTC, Misieq01 commented on src/containers/floating/StagedSecurity/sections/SeedPhrase/SeedPhrase.tsx
> +    useEffect(() => {
What about removing hooks and just moving this loop to function outside component like `const groupSeedWords = (words: string[]) => {}` and then even you can do `groupSeedWords(words).map((group, groupIndex) => ...`

2025-01-09 11:15 UTC, Misieq01 commented on src/hooks/mining/useMiningMetricsUpdater.ts
>                  const isMining = metrics.cpu?.mining.is_mining || metrics.gpu?.mining.is_mining;
These checks for node_connection and setting animation are no longer needed or they were moved somewhere else ?

2025-01-09 11:21 UTC, shanimal08 commented on src/hooks/mining/useMiningMetricsUpdater.ts
>                  const isMining = metrics.cpu?.mining.is_mining || metrics.gpu?.mining.is_mining;
not needed since `useUiMiningStateMachine` checks against is_mining (gpu & cpu), so that actually caused a bit of weirdness with the animation states and i think `is_mining` for either is connected to being connected already on the BE? (could be wrong about that though)

2025-01-09 11:38 UTC, Misieq01 commented on src/hooks/mining/useMiningMetricsUpdater.ts
>                  const isMining = metrics.cpu?.mining.is_mining || metrics.gpu?.mining.is_mining;
I was assuming that if someone added it then you can have `is_mining = true` and then `metrics.base_node?.is_connected either true or false` and when user wasn't connected to node then we didn't wanted to show animation of mining. I'm not sure but that's why I asked

2025-01-09 11:39 UTC, shanimal08 commented on src/containers/floating/StagedSecurity/sections/SeedPhrase/SeedPhrase.tsx
> +    useEffect(() => {
nice that did the trick :D updated :D

2025-01-09 12:02 UTC, MCozhusheck commented on src-tauri/src/main.rs
> +
> neat, thanks! should i do the same for the `miner_metrics` emit loop just above?:D

yes previous could be written similar

2025-01-09 12:02 UTC, MCozhusheck approved these changes

2025-01-09 14:07 UTC, Misieq01 commented on src/hooks/mining/useMiningMetricsUpdater.ts
>                  const isMining = metrics.cpu?.mining.is_mining || metrics.gpu?.mining.is_mining;
Yeah I was thinking the same but someone added code that works like if there could be case where `base_node.connected` can be `false` and `is_mining` `true` so that's why I asked if you know for sure that this is not a case hah

2025-01-10 08:43 UTC, shanimal08 commented on src/hooks/mining/useMiningMetricsUpdater.ts
>                  const isMining = metrics.cpu?.mining.is_mining || metrics.gpu?.mining.is_mining;
rats! oki awesome fixing, thanks so much!

2025-01-10 11:49 UTC, shanimal08 commented on src-tauri/Cargo.lock
> +version = "0.2.0"
nice catch :D i just reverted to what it was before the tauri x tari fork but this branch is so old that a bunch of things have newer releases 😅 updated, ty!

2025-01-15 11:42 UTC, merged