fix: broken-seed-words-after-restart
tari-project/universe pull request #1263
Opened 2024-12-13 12:52 UTC by Misieq01

## Fixes #1203 

### [ Summary ]
- Marked wallet directory for skipping deletion when `reset_wallet` is false
- Added extra check for omitting keychain items in deletion process when `reset_wallet` is false

2024-12-24 16:02 UTC, brianp requested changes
This mostly looks good. Where it fails is in the MacOS implementation.

When a user first creates the wallet if they deny access to the keychain it creates a backup file in the root application directory `credentials_backup.bin`. This file becomes lost during the reset. So only in the case where credentials are not stored in the keychain the seed words still become lost. 
When stored in the keychain this PR works fine.

We can't simply move the location of the file though, as this would be a breaking change for anyone who already has the file located in the current location.

To correct this situation we would need to migrate the file to the new location in the wallet directory for existing users to ensure a smooth upgrade process.

2025-01-10 09:54 UTC, brianp requested changes
Update doesn't work as expected. The `credentials_backup.bin` file is still removed.

This happens because the filename was added to a `folder_block_list`. This list is checked to see if the members of the list are directories. Which `credentials_backup.bin` is not.

2025-01-10 11:00 UTC, Misieq01 commented
@brianp Sorry, my bad, got lost in ifs and had problems with testing it properly. Thought it would work and waited for someone to test it. I think now it should be working but my mac still do not cooperate with me so I can't test it

2025-01-14 10:53 UTC, brianp approved these changes

2025-01-14 10:54 UTC, brianp commented
Tested and looks good 👍🏻

2025-01-14 10:54 UTC, merged

2025-01-20 07:13 UTC, Tas4tari commented
Tested on Windows 11, app version 0.8.44 and this is now working

2025-01-21 07:50 UTC, Anziskavds commented
Tested successfully on MacBook Air M1 2020 13 inch on Sequoia 15.2 on v0.8.44.