fix(ui): systray format
tari-project/universe pull request #471
Opened 2024-09-13 11:17 UTC by karczuRF

Description
Fix system data formatting

Motivation and Context
Resolves #419 

How Has This Been Tested?
Manually

What process can a PR reviewer use to test or verify this change?
**MUST BE YET TESTED ON WINDOWS**

Breaking Changes
---

- [x] None
- [ ] Requires data directory on base node to be deleted
- [ ] Requires hard fork
- [ ] Other - Please specify

2024-09-18 09:05 UTC, stringhandler commented on src-tauri/src/systemtray_manager.rs
> +                    Formatter::new().with_decimals(2).with_separator("").format(data.cpu_hashrate),
```suggestion
                    Formatter::new().with_decimals(0).with_separator("").format(data.cpu_hashrate),
```
I think 0 decimals is sufficient

2024-10-02 11:11 UTC, stringhandler approved these changes

2024-10-24 14:19 UTC, brianp requested changes
![image](https://github.com/user-attachments/assets/ac326439-eebe-4188-a27d-cc507504c040)

Estimated earnings per day has quotes around it, and only seems to be calculated based on CPU, not combined with GPU.

2024-10-25 06:36 UTC, brianp approved these changes
Looks much better 👍🏻 

<img width="585" alt="image" src="https://github.com/user-attachments/assets/27bdab79-4dab-4307-94dc-647f14242e32">

2024-10-25 06:37 UTC, merged

2024-11-01 12:24 UTC, Tas4tari commented
Tested on Windows 11, app version 0.5.60 and the sys tray format appears cut off
![Screenshot (182)](https://github.com/user-attachments/assets/3d884405-3c6b-49ec-ad27-19df86714cee)