feat: add-option-to-auto-start-mining-after-app-startup
tari-project/universe pull request #531
Opened 2024-09-19 11:29 UTC by Misieq01

### [ Features ]
- Added `mine_on_app_start` flag for automatically start mining after app setup finish
- Added option in settings for toggling mentioned flag
------------
### [ Testing ]
 Enable or disable option in settings and restart app

2024-09-19 16:52 UTC, Krakaw approved these changes
LGTM

2024-09-19 16:52 UTC, Krakaw commented on src/containers/SideBar/components/Settings/MiningSettings.tsx
> +        console.log('Toggling mining on app start', event.target.checked);
We can remove this
```suggestion
```

2024-09-19 16:56 UTC, Krakaw commented
@Misieq01 please can you fix the conflicts and push.

2024-09-25 10:31 UTC, stringhandler commented
This is not 100% solving the issue #122. When I restart my computer, Tari Universe must also restart. The user should be given an option in settings:
* [ ] Start Tari Universe when I log on

Which when ticked, should start when a user reboots or logs out of windows and logs in again. 
We only need to target Macos and Windows for this.

2024-09-25 10:32 UTC, stringhandler requested changes
See comment

2024-10-15 12:49 UTC, brianp approved these changes
Tested on MacOS.

Validated mine on start setting did not mine on start when toggled off, and did mine on start when toggled on.

Validated start on login worked after restart, and the login item was removed when toggled off.

2024-10-15 12:50 UTC, merged

2024-10-16 06:14 UTC, Tas4tari commented
Tested successfully on Releasee version 0.5.24 on Windows 11