fix: change wording on block sync to be more clear
tari-project/universe pull request #878
Opened 2024-10-17 11:47 UTC by stringhandler

![image](https://github.com/user-attachments/assets/05f222e5-b082-4f15-bf3d-efe08d15f50a)

2024-10-25 11:02 UTC, brianp requested changes

2024-10-25 11:02 UTC, brianp commented on public/locales/en/setup-view.json
> +        "waiting-for-header-sync": "Waiting for header sync. {{local_header_height}}/{{tip_header_height}} headers and {{local_block_height}}/{{tip_block_height}} block synced. ",
```suggestion
        "waiting-for-header-sync": "Waiting for header sync. {{local_header_height}}/{{tip_header_height}} headers and {{local_block_height}}/{{tip_block_height}} blocks synced. ",
```

2024-10-25 11:02 UTC, brianp commented on src-tauri/src/process_watcher.rs
> +                               sleep(Duration::from_secs(3)).await;
Is this relevant to this PR?

2024-10-25 11:14 UTC, stringhandler commented on src-tauri/src/process_watcher.rs
> +                               sleep(Duration::from_secs(3)).await;
lol no

2024-11-05 11:21 UTC, merged

2024-11-06 08:58 UTC, Tas4tari commented
Tested successfully on Windows 11, app version 0.5.63

2024-11-06 12:17 UTC, Anziskavds commented
Tested successfully on MacBook Air 13 inch M1 2020 on Testnet v0.5.63.