feat(ui): flex & share history transaction modal
tari-project/universe pull request #974
Opened 2024-10-30 09:49 UTC by peps

This PR adds the UI for sharing specific transactions in the History list. 

To enable: 

1) in `useShareRewardStore.ts` change `sharingEnabled: false` to `sharingEnabled: true`
2) Make sure you're logged in to airdrop ( it's disabled unless you're logged in )

Note: This can be merged in it's disabled state, but DO NOT launch it publicly until the share card work is completed on the airdrop website side. 

![CleanShot 2024-10-30 at 17 45 52](https://github.com/user-attachments/assets/5facb686-367f-442f-b294-cf336e544c09)

![CleanShot 2024-10-30 at 17 46 22](https://github.com/user-attachments/assets/e1e339f7-29de-40a1-9486-53e47cf82c5c)

2024-10-30 09:59 UTC, peps commented on src/store/useShareRewardStore.ts
> +    sharingEnabled: false,
Set this to `true` to enable the ui

2024-10-31 23:40 UTC, brianp requested changes
When "Show history" is clicked the UX completely falls apart, and the app breaks. Let me know if I'm doing something wrong. I've enabled the feature as described, and everything looks normal until that point.

2024-11-01 09:28 UTC, peps commented
> When "Show history" is clicked the UX completely falls apart, and the app breaks. Let me know if I'm doing something wrong. I've enabled the feature as described, and everything looks normal until that point.

Looks like a bad merge, fixing it now

2024-11-01 09:35 UTC, peps commented
@brianp should be good now

2024-11-05 11:36 UTC, brianp commented
PR now works after merge fixes. You may want to apply similar modal sizing fixes though. It is scrollable, so I'm going to merge. Up to you to submit sizing fixes if that sorta thing is up your alley.

<img width="1376" alt="image" src="https://github.com/user-attachments/assets/bd4cfded-8f31-492a-b23c-1af37244c0c0">
<img width="1380" alt="image" src="https://github.com/user-attachments/assets/a900406f-b245-49f5-b51e-48e68ad20300">

2024-11-05 11:36 UTC, brianp approved these changes

2024-11-05 12:19 UTC, merged

2024-11-06 12:23 UTC, Anziskavds commented
Tested unsuccessfully on MacBook Air 13 inch M1 2020 on Testnet v0.5.63.

<img width="416" alt="image" src="https://github.com/user-attachments/assets/6bec4090-68ed-4840-a357-ca10395bb3dd">